psychoanalyst_task:
  description: >
    ask five questions to user about {topic}.
  expected_output: >
    A list of five questions and their answers about {topic}
  agent: psychoanalyst

psychoanalyst_reporter_task:
  description: >
    Analyse the list of questions and answers and suggest a therapy to the user.
  expected_output: >
    A therapy suggestion based on the five questions and answers about {topic}
  agent: psychoanalyst_reporter
